### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by PiggleMcDiggle** [HorizonsEndMC/Ion#73]
It is a serious issue that my college blocks Discord.

This is bypassing and maybe against acceptable use policy?

I can still get notifications from Discord, amazingly.

Peter, that proposed bug fix is extremely funny due to how it will never even prevent what it is trying to and does not even address interactions between multiblocks.

**Comment by PiggleMcDiggle** [comment]
![Screenshot_20220110-111232_Chrome](https://user-images.githubusercontent.com/56192681/148756946-3901c8c2-d519-430a-a850-870bfd66194f.jpg)
Qapla'.
Bypass successful.

**Comment by PiggleMcDiggle** [comment]
I burnt through a gigabyte in discord calls.  It's all I have...

**Comment by PiggleMcDiggle** [comment]
I should probably get a better way to bypass, because I miss some notifications.

I should see every ping though.

**Comment by PiggleMcDiggle** [comment]
Good idea, thank you.

I would assume Minecraft servers are blocked, however.

**Comment by PiggleMcDiggle** [comment]
@Doctor(_)Xeno#8300 test

**Comment by PiggleMcDiggle** [comment]
And my notifications no longer appear to be working.

If you need a response from me, message me through GitHub, I suppose.

**Comment by PiggleMcDiggle** [comment]
Know this person, Peter?

https://github.com/alpha-pulsar

**Comment by PiggleMcDiggle** [comment]
![Screenshot_20220111-134137_One UI Home](https://user-images.githubusercontent.com/56192681/148953501-4f2ce7d6-3561-49e2-a7a8-33cdb3aed342.jpg)


Why is this the first thing I see after a Physics exam?

**Comment by Peter-Crawley** [comment]
![Screenshot_20220111-134557.png](https://user-images.githubusercontent.com/49043380/148954098-759e47b7-03d7-48ad-8ccf-4bcdc9f1491c.png)

**Comment by PiggleMcDiggle** [comment]
We are strong.

**Comment by PiggleMcDiggle** [comment]
I'll be back by 16:00 again today.

Have a useless one hour session about Kooth.

**Comment by trainb0y1** [comment]
Why is this a thing :pain:

**Comment by PiggleMcDiggle** [comment]
I see that Sciath knows his rules of acquisition.

**Comment by SciathGH** [comment]
what does that mean

**Comment by SciathGH** [comment]
Btw just use a vpn, or even try web discord

**Comment by PiggleMcDiggle** [comment]
No mobile signal.

I cannot see your  DMs.

**Comment by Peter-Crawley** [comment]
Shame, you will have to wait then

**Comment by Peter-Crawley** [comment]
It is quite funny though

**Comment by PiggleMcDiggle** [comment]
I've only got 45 minutes of RE to go.

I saw "Visual Basic" so it must be hilarious.

**Comment by PiggleMcDiggle** [comment]
![Screenshot_20220201-135932_Drive](https://user-images.githubusercontent.com/56192681/151982085-6db2598e-c4c1-4de9-87fb-914c4e564d05.jpg)
Fascinating image.

**Comment by PiggleMcDiggle** [comment]
@SciathGH 
![Screenshot_20220209-143143_Desmos](https://user-images.githubusercontent.com/56192681/153222255-614e98f3-d386-464e-b30f-0acdd06c26a7.jpg)

**Comment by trainb0y1** [comment]
I’m still confused as to how you can get push notifications but not access discord…

**Comment by PiggleMcDiggle** [comment]
> I’m still confused as to how you can get push notifications but not access discord…

![Screenshot_20220209-143643_Discord](https://user-images.githubusercontent.com/56192681/153223054-26195a8c-2aab-4e27-ab71-4664e43bcd62.jpg)

**Comment by PiggleMcDiggle** [comment]
What is your idea?

**Comment by trainb0y1** [comment]
![F1ED82BA-1422-4EAD-A886-A587FFEE774E](https://user-images.githubusercontent.com/66213737/153223818-40f5d088-e4a3-434a-82b2-3d11188dc99a.jpeg)
