### ISSUE TITLE
Blaster Cannon Issues

### ISSUE THREAD

**Issue by Ashparty** [HorizonsEndMC/Ion#79]
Mobs hit with a blast from a blaster cannon (the explosion) do not gain any damage, and when mobs are hit with a direct beam from a blaster cannon it does NOT summon an explosion (Intentional?)

**Comment by trainb0y1** [comment]
I changed basically nothing of the blaster code when working on custom items. The no explosion on entity hit was definitely a thing on SL, I'm not sure whether or not it was intentional though.

**Comment by trainb0y1** [comment]
The only thing I did was get rid of the dumb enum BlasterType

**Comment by Peter-Crawley** [comment]
Was this on the testing server or the main server?

**Comment by Ashparty** [comment]
> 

Was on the Testing server while you were steaming

**Comment by trainb0y1** [comment]
Some insight from Blackular:
> It's intentional, otherwise it does fucky things if you're flying with jet boots like yeeting you through solid walls and other shenanigans
was reading your dev stuff, and it's purposeful  

> also an issue is if it hits a player without jet boots it's GG wp
they fall into a hole they can't escape from and then you throw a thermal det in like the old days  

Maybe it should explode when hitting entities that aren't players?
